node test/root.js &&
node test/collection.js &&
node test/collection-freeze.js &&
#node test/collection-get.js &&
node test/item.js &&
node test/item-already-init.js &&
node test/item-bid.js &&
node test/item-bid-prolong.js &&
node test/item-freeze.js &&
node test/item-delete-record.js &&
node test/item-edit-record.js &&
node test/item-fill-up.js &&
node test/item-finish-auction-change-content.js &&
node test/item-get.js &&
node test/item-get-2.js &&
node test/item-get-static-data.js &&
node test/item-loss.js &&
node test/item-transfer.js &&
echo "OK"